name: Deploy to gh-pages
on:
  push:
    branches: ["main"]  # Build when pushing to main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: |
          cd code-assist-webUI/code-assist-web
          npm run build & node server.js & npm start # Replace with your actual build command
          # Move build output to root /docs
          mv build ../docs  # Adjust paths to match your build output

      - name: Add .nojekyll
        run: touch docs/.nojekyll  # Disable Jekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # Explicitly deploy to this branch
          publish_dir: ./docs  # Deploy the root docs folder
          force_orphan: true  # Clean old files