name: Deploy to GitHub Pages
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          cd code-assist-webUI/code-assist-web
          npm ci

      - name: Build app
        run: |
          cd code-assist-webUI/code-assist-web
          npm run build  # Builds to root/docs

      - name: Add .nojekyll
        run: touch docs/.nojekyll

      - name: Generate index.json
        run: |
          node scripts/generate-index.js

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add code-assist-webUI/code-assist-web/src/prompt-results/index.json
          git commit -m "Auto-update index.json" || echo "No changes to commit"
          git push

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          force_orphan: true